// Generated by gencpp from file sensor_listener/InitHaltAPI.msg
// DO NOT EDIT!


#ifndef SENSOR_LISTENER_MESSAGE_INITHALTAPI_H
#define SENSOR_LISTENER_MESSAGE_INITHALTAPI_H

#include <ros/service_traits.h>


#include <sensor_listener/InitHaltAPIRequest.h>
#include <sensor_listener/InitHaltAPIResponse.h>


namespace sensor_listener
{

struct InitHaltAPI
{

typedef InitHaltAPIRequest Request;
typedef InitHaltAPIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitHaltAPI
} // namespace sensor_listener


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_listener::InitHaltAPI > {
  static const char* value()
  {
    return "ebaac739ca0ec34f8c8978d1e8915ec0";
  }

  static const char* value(const ::sensor_listener::InitHaltAPI&) { return value(); }
};

template<>
struct DataType< ::sensor_listener::InitHaltAPI > {
  static const char* value()
  {
    return "sensor_listener/InitHaltAPI";
  }

  static const char* value(const ::sensor_listener::InitHaltAPI&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_listener::InitHaltAPIRequest> should match 
// service_traits::MD5Sum< ::sensor_listener::InitHaltAPI > 
template<>
struct MD5Sum< ::sensor_listener::InitHaltAPIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_listener::InitHaltAPI >::value();
  }
  static const char* value(const ::sensor_listener::InitHaltAPIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_listener::InitHaltAPIRequest> should match 
// service_traits::DataType< ::sensor_listener::InitHaltAPI > 
template<>
struct DataType< ::sensor_listener::InitHaltAPIRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_listener::InitHaltAPI >::value();
  }
  static const char* value(const ::sensor_listener::InitHaltAPIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_listener::InitHaltAPIResponse> should match 
// service_traits::MD5Sum< ::sensor_listener::InitHaltAPI > 
template<>
struct MD5Sum< ::sensor_listener::InitHaltAPIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_listener::InitHaltAPI >::value();
  }
  static const char* value(const ::sensor_listener::InitHaltAPIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_listener::InitHaltAPIResponse> should match 
// service_traits::DataType< ::sensor_listener::InitHaltAPI > 
template<>
struct DataType< ::sensor_listener::InitHaltAPIResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_listener::InitHaltAPI >::value();
  }
  static const char* value(const ::sensor_listener::InitHaltAPIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_LISTENER_MESSAGE_INITHALTAPI_H
