// Generated by gencpp from file sensor_listener/InitHaltAPIResponse.msg
// DO NOT EDIT!


#ifndef SENSOR_LISTENER_MESSAGE_INITHALTAPIRESPONSE_H
#define SENSOR_LISTENER_MESSAGE_INITHALTAPIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_listener
{
template <class ContainerAllocator>
struct InitHaltAPIResponse_
{
  typedef InitHaltAPIResponse_<ContainerAllocator> Type;

  InitHaltAPIResponse_()
    : status(0)  {
    }
  InitHaltAPIResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
    }



   typedef int64_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitHaltAPIResponse_

typedef ::sensor_listener::InitHaltAPIResponse_<std::allocator<void> > InitHaltAPIResponse;

typedef boost::shared_ptr< ::sensor_listener::InitHaltAPIResponse > InitHaltAPIResponsePtr;
typedef boost::shared_ptr< ::sensor_listener::InitHaltAPIResponse const> InitHaltAPIResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_listener

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_listener': ['/home/jorgearraez/catkin_ws/src/sensor_listener/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4107476a6271fc2684d94be17d33f854";
  }

  static const char* value(const ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4107476a6271fc26ULL;
  static const uint64_t static_value2 = 0x84d94be17d33f854ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_listener/InitHaltAPIResponse";
  }

  static const char* value(const ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 status\n\
\n\
";
  }

  static const char* value(const ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct InitHaltAPIResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_listener::InitHaltAPIResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int64_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_LISTENER_MESSAGE_INITHALTAPIRESPONSE_H
