// Generated by gencpp from file sensor_listener/PositionAPICoordSpaceQuat.msg
// DO NOT EDIT!


#ifndef SENSOR_LISTENER_MESSAGE_POSITIONAPICOORDSPACEQUAT_H
#define SENSOR_LISTENER_MESSAGE_POSITIONAPICOORDSPACEQUAT_H

#include <ros/service_traits.h>


#include <sensor_listener/PositionAPICoordSpaceQuatRequest.h>
#include <sensor_listener/PositionAPICoordSpaceQuatResponse.h>


namespace sensor_listener
{

struct PositionAPICoordSpaceQuat
{

typedef PositionAPICoordSpaceQuatRequest Request;
typedef PositionAPICoordSpaceQuatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionAPICoordSpaceQuat
} // namespace sensor_listener


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuat > {
  static const char* value()
  {
    return "45a02fe99f84dd40c7ccb9d91e95f715";
  }

  static const char* value(const ::sensor_listener::PositionAPICoordSpaceQuat&) { return value(); }
};

template<>
struct DataType< ::sensor_listener::PositionAPICoordSpaceQuat > {
  static const char* value()
  {
    return "sensor_listener/PositionAPICoordSpaceQuat";
  }

  static const char* value(const ::sensor_listener::PositionAPICoordSpaceQuat&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuatRequest> should match 
// service_traits::MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuat > 
template<>
struct MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuat >::value();
  }
  static const char* value(const ::sensor_listener::PositionAPICoordSpaceQuatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_listener::PositionAPICoordSpaceQuatRequest> should match 
// service_traits::DataType< ::sensor_listener::PositionAPICoordSpaceQuat > 
template<>
struct DataType< ::sensor_listener::PositionAPICoordSpaceQuatRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_listener::PositionAPICoordSpaceQuat >::value();
  }
  static const char* value(const ::sensor_listener::PositionAPICoordSpaceQuatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuatResponse> should match 
// service_traits::MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuat > 
template<>
struct MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuat >::value();
  }
  static const char* value(const ::sensor_listener::PositionAPICoordSpaceQuatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_listener::PositionAPICoordSpaceQuatResponse> should match 
// service_traits::DataType< ::sensor_listener::PositionAPICoordSpaceQuat > 
template<>
struct DataType< ::sensor_listener::PositionAPICoordSpaceQuatResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_listener::PositionAPICoordSpaceQuat >::value();
  }
  static const char* value(const ::sensor_listener::PositionAPICoordSpaceQuatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_LISTENER_MESSAGE_POSITIONAPICOORDSPACEQUAT_H
