// Generated by gencpp from file sensor_listener/PositionAPICoordSpaceQuatResponse.msg
// DO NOT EDIT!


#ifndef SENSOR_LISTENER_MESSAGE_POSITIONAPICOORDSPACEQUATRESPONSE_H
#define SENSOR_LISTENER_MESSAGE_POSITIONAPICOORDSPACEQUATRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_listener
{
template <class ContainerAllocator>
struct PositionAPICoordSpaceQuatResponse_
{
  typedef PositionAPICoordSpaceQuatResponse_<ContainerAllocator> Type;

  PositionAPICoordSpaceQuatResponse_()
    : ret(0)  {
    }
  PositionAPICoordSpaceQuatResponse_(const ContainerAllocator& _alloc)
    : ret(0)  {
    }



   typedef int64_t _ret_type;
  _ret_type ret;




  typedef boost::shared_ptr< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PositionAPICoordSpaceQuatResponse_

typedef ::sensor_listener::PositionAPICoordSpaceQuatResponse_<std::allocator<void> > PositionAPICoordSpaceQuatResponse;

typedef boost::shared_ptr< ::sensor_listener::PositionAPICoordSpaceQuatResponse > PositionAPICoordSpaceQuatResponsePtr;
typedef boost::shared_ptr< ::sensor_listener::PositionAPICoordSpaceQuatResponse const> PositionAPICoordSpaceQuatResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_listener

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_listener': ['/home/jorgearraez/catkin_ws/src/sensor_listener/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2522e220fa06fe7901e82fcde5a0bb66";
  }

  static const char* value(const ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2522e220fa06fe79ULL;
  static const uint64_t static_value2 = 0x01e82fcde5a0bb66ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_listener/PositionAPICoordSpaceQuatResponse";
  }

  static const char* value(const ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 ret\n\
\n\
";
  }

  static const char* value(const ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PositionAPICoordSpaceQuatResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_listener::PositionAPICoordSpaceQuatResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_LISTENER_MESSAGE_POSITIONAPICOORDSPACEQUATRESPONSE_H
