// Generated by gencpp from file sensor_listener/PositionAPICoordSpace.msg
// DO NOT EDIT!


#ifndef SENSOR_LISTENER_MESSAGE_POSITIONAPICOORDSPACE_H
#define SENSOR_LISTENER_MESSAGE_POSITIONAPICOORDSPACE_H

#include <ros/service_traits.h>


#include <sensor_listener/PositionAPICoordSpaceRequest.h>
#include <sensor_listener/PositionAPICoordSpaceResponse.h>


namespace sensor_listener
{

struct PositionAPICoordSpace
{

typedef PositionAPICoordSpaceRequest Request;
typedef PositionAPICoordSpaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionAPICoordSpace
} // namespace sensor_listener


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_listener::PositionAPICoordSpace > {
  static const char* value()
  {
    return "f3eb575d9518a9ccc09a6926e4a48227";
  }

  static const char* value(const ::sensor_listener::PositionAPICoordSpace&) { return value(); }
};

template<>
struct DataType< ::sensor_listener::PositionAPICoordSpace > {
  static const char* value()
  {
    return "sensor_listener/PositionAPICoordSpace";
  }

  static const char* value(const ::sensor_listener::PositionAPICoordSpace&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_listener::PositionAPICoordSpaceRequest> should match 
// service_traits::MD5Sum< ::sensor_listener::PositionAPICoordSpace > 
template<>
struct MD5Sum< ::sensor_listener::PositionAPICoordSpaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_listener::PositionAPICoordSpace >::value();
  }
  static const char* value(const ::sensor_listener::PositionAPICoordSpaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_listener::PositionAPICoordSpaceRequest> should match 
// service_traits::DataType< ::sensor_listener::PositionAPICoordSpace > 
template<>
struct DataType< ::sensor_listener::PositionAPICoordSpaceRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_listener::PositionAPICoordSpace >::value();
  }
  static const char* value(const ::sensor_listener::PositionAPICoordSpaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_listener::PositionAPICoordSpaceResponse> should match 
// service_traits::MD5Sum< ::sensor_listener::PositionAPICoordSpace > 
template<>
struct MD5Sum< ::sensor_listener::PositionAPICoordSpaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_listener::PositionAPICoordSpace >::value();
  }
  static const char* value(const ::sensor_listener::PositionAPICoordSpaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_listener::PositionAPICoordSpaceResponse> should match 
// service_traits::DataType< ::sensor_listener::PositionAPICoordSpace > 
template<>
struct DataType< ::sensor_listener::PositionAPICoordSpaceResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_listener::PositionAPICoordSpace >::value();
  }
  static const char* value(const ::sensor_listener::PositionAPICoordSpaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_LISTENER_MESSAGE_POSITIONAPICOORDSPACE_H
